# Generated by Django 5.0.5 on 2024-05-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=60)),
                ('patient_username', models.CharField(blank=True, max_length=40, null=True)),
                ('department', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('patient_phonenumber', models.IntegerField()),
                ('patient_email', models.EmailField(max_length=254)),
                ('doctor_phonenumber', models.IntegerField(blank=True, null=True)),
                ('doctor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('symptoms', models.TextField()),
                ('prescription', models.TextField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=40)),
                ('Doctor_name', models.CharField(max_length=40)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=100, null=True)),
                ('admit_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('day_spent', models.PositiveIntegerField(blank=True, null=True)),
                ('room_charge', models.PositiveIntegerField(blank=True, null=True)),
                ('medicine_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('doctor_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('other_charge', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
